# -*- coding: utf-8 -*-
"""Linearregression demo mini.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EQQaHCvf3HLeDorHOdKXek1KH0pL66R1
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('/content/salary-experience-dataset.csv')
x = dataset.iloc[:,0].values
y = dataset.iloc[:,1].values

print(x)
print(x.shape)
print(y, y.shape)
x = np.reshape(x,(-1,1))
y = np.reshape(y,(-1,1))
print(x.shape)
print(y.shape)

plt.scatter(x,y,color = 'red')
plt.title('salary vs experience')
plt.xlabel('years of experience')
plt.ylabel('salary')
plt.show()

from sklearn.linear_model import LinearRegression
regressor_1 = LinearRegression()
regressor_1.fit(x,y)

plt.scatter(x,y,color = 'red')
plt.plot(x,regressor_1.predict(x), color = 'blue')
plt.title('salary vs experience')
plt.xlabel('years of experience')
plt.ylabel('salary')
plt.show()

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 1/3, random_state = 0)
print(x_train.shape)
print(x_test.shape)

plt.scatter(x_train, y_train, color = 'red')
plt.scatter(x_test, y_test, color = 'blue')
plt.title('salary vs experience')
plt.xlabel('years of experience')
plt.ylabel('salary')
plt.show()

regressor_2 = LinearRegression()
regressor_2.fit(x_train,y_train)
y_pred = regressor_2.predict(x_test)

plt.scatter(x_test, y_test, color = 'blue')
#plt.scatter(x_test, y_pred, color = 'blue')
plt.plot(x_test, y_pred, color = 'black')
plt.title('salary vs experience')
plt.xlabel('years of experience')
plt.ylabel('salary')
plt.show()

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
print('MSE', mean_squared_error(y_test, y_pred))
print('MAE', mean_absolute_error(y_test, y_pred))

"""# New Section"""

